theme: jekyll-theme-cayman
title: Portfolio

include:
  - assets/css/custom.css

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/style.scss"
